name: Acciojob Tests

on:
  push:
    branches: [ "main", "master" ]

jobs:
  prepare-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  run-acciojob-tests:
    uses: acciojob/acciojob-tests-action/.github/workflows/main-action.yml@main
    needs: prepare-and-test
    secrets: inherit
